---
version: '3'

services:
  django:
    build: .
    image: collab/core
    container_name: collab-core
    volumes:
      - .:/app
    networks:
      - collab
    depends_on:
      - postgres
      - redis
    profiles: ['collab']
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 8001:8001

  redis:
    image: redis:alpine
    container_name: collab-redis
    volumes:
      - redis:/var/lib/redis
    networks:
      - collab
    profiles: ['collab']

  postgres:
    image: postgres:alpine
    container_name: collab-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - collab
    profiles: ['collab']
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432


volumes:
  redis:
  postgres:

networks:
  collab:
